# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import market_data_proto_pb2 as market__data__proto__pb2


class MarketDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetKlineData = channel.unary_unary(
                '/market_data.MarketDataService/GetKlineData',
                request_serializer=market__data__proto__pb2.request.SerializeToString,
                response_deserializer=market__data__proto__pb2.response.FromString,
                )
        self.GetOrderBookData = channel.unary_unary(
                '/market_data.MarketDataService/GetOrderBookData',
                request_serializer=market__data__proto__pb2.ob_request.SerializeToString,
                response_deserializer=market__data__proto__pb2.ob_response.FromString,
                )


class MarketDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetKlineData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderBookData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetKlineData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKlineData,
                    request_deserializer=market__data__proto__pb2.request.FromString,
                    response_serializer=market__data__proto__pb2.response.SerializeToString,
            ),
            'GetOrderBookData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderBookData,
                    request_deserializer=market__data__proto__pb2.ob_request.FromString,
                    response_serializer=market__data__proto__pb2.ob_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'market_data.MarketDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MarketDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetKlineData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/market_data.MarketDataService/GetKlineData',
            market__data__proto__pb2.request.SerializeToString,
            market__data__proto__pb2.response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrderBookData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/market_data.MarketDataService/GetOrderBookData',
            market__data__proto__pb2.ob_request.SerializeToString,
            market__data__proto__pb2.ob_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
